Add more specific err message for invalid struct
Ackee-Blockchain/trident pull request #164
Opened 2024-05-22 08:13 UTC by cryptopapi997

Follow up from https://github.com/Ackee-Blockchain/trident/issues/160 , where the issue was camel -> kebab -> camel case conversion isn't always constant. This was hard to determine since trident didn't say which struct was the problem. Saying which one it was (and seeing that it sees it incorrectly capitalized) would've made this easy to debug, so this PR changes this. 

Maybe trident not supporting vars with multiple sequential capital letters could be specified in the docs somewhere too, but wasn't sure where the best spot for this is, so up to you guys.

2024-05-22 09:15 UTC, lukacan commented
Hello @cryptopapi997 , thanks for the PR , we will have a look and get back to you later :)

2024-05-23 12:35 UTC, lukacan requested changes

2024-05-23 12:35 UTC, lukacan commented on crates/client/src/idl.rs
> +                "instruction struct".to_string(),
What about also including the "instruction_struct_name" here?

2024-05-25 09:22 UTC, cryptopapi997 commented
Adapted according to your review, feel free to take another look @lukacan

2024-05-29 11:10 UTC, Ikrk commented
Hi @cryptopapi997, thank you, it looks good to me!
Can you please rebase your branch on develop and change this PR to merge to develop branch?  We are currently pushing new features into develop branch and merge to master only on release. 

We might however reconsider this branching strategy in the (short) future in order to make contributions easier...

2024-05-29 11:36 UTC, cryptopapi997 commented
Got it, just rebased & resolved merge conflicts - feel free to take a final look @Ikrk

2024-05-29 11:47 UTC, Ikrk approved these changes

2024-05-29 11:48 UTC, merged

2024-05-29 11:49 UTC, Ikrk commented
Thanks, merged!